### ISSUE TITLE
AMI Version is parsed wrong

### ISSUE THREAD

**Issue by furkanturan** [Xilinx/AVED#7]
AMI compilation starts with version derivation from the git commit tag, [which happens in `AVED/sw/AMI/scripts/getVersion.sh`](https://github.com/Xilinx/AVED/blob/b580f840109718b09dd504517b40abca8b9d68d5/sw/AMI/scripts/getVersion.sh#L103).

However, the git commit tags do not seem to match with the expected format. The expected format is `x.x.x`, while the tags look like `amd_v80p_gen5x8_23.2_exdes_1_20231204`. This mismatch causes parsing the version wrongly, so AMI compilation fails. Furthermore, what should be the correct version is missing.

If I check the AMC version at `fw/AMC/merge_amc_version.json`, I would expect AMI version to be also same. That makes sense considering the [documentation page](https://xilinx.github.io/AVED/amd_v80_gen5x8_exdes_2_20240408/AVED+Updating+Design+PDI+in+Flash.html) which says

> When using this approach it is important to make sure that the version of AMI is compatible with the version of AMC which is running on the card (compatibility is indicated by having the same Major & Minor version numbers in the AMI/AMC Major.Minor.Patch version number format.)

After reading this line, I would expect AMI and AMC from same git release/branch/tag to have same version numbers. Yet, I am doubtful, if that is the case. If `getVersion.sh` would not be called, the default [AMC version here](https://github.com/Xilinx/AVED/blob/main/fw/AMC/merge_amc_version.json) and the default [AMI version here](https://github.com/Xilinx/AVED/blob/main/sw/AMI/ami_version.json) do not match, which is against the recommendation at above referred documentation.

**Comment by nbrown104** [comment]
This will be addressed in the 24.1 update. In the meantime, it can be addressed manually by:
```
cd sw/AMI
cp getVersion.sh scripts/getVersion.sh
```
