### ISSUE TITLE
The link to download amd_v80_gen5x8_24.1_xbtest_stress_20241002.zip

### ISSUE THREAD

**Issue by PeterCCChang** [Xilinx/AVED#8]
Hi,
According to the document as below, there is new version AVED project file.
https://xilinx.github.io/AVED/amd_v80_gen5x8_24.1_20241002/AVED+Deployment+Archive.html
But we can't find the link to download it.
Could you advise the link?
Thanks.

**Comment by oldcityustc** [comment]
Got the same issue here.

**Comment by nbrown104** [comment]
https://xilinx.github.io/AVED/amd_v80_gen5x8_24.1_20241002/AVED%2BRelease%2BInformation.html - TBD

**Comment by nbrown104** [comment]
Latest AVED project files now released.
