### ISSUE TITLE
Compilation problems with sw/AMI Testing

### ISSUE THREAD

**Issue by jmoya82** [Xilinx/AVED#9]
Hi there,

Referring to https://github.com/Xilinx/AVED/tree/main/sw/AMI#testing, I am getting the following error:

<img width="1508" alt="Screenshot 2024-10-25 at 08 59 05" src="https://github.com/user-attachments/assets/57869efc-4adf-4ba6-b38a-08057d43b6dc">

How should I proceed to solve the compilation process? 

I would have the following additional questions:
1. How do I run the test once compiled?
2. Is the test being run the same as xbtest is doing?

**Comment by nbrown104** [comment]
The test build within the individual sw/AMI directories is for development unit testing only, and requires CMocka in the specified path to function. It is not part of the AVED release and is released as source only for reference.
